(deftheme nord-prlg
  "Created 2024-10-21.")

(custom-theme-set-variables
 'nord-prlg
 '(connection-local-profile-alist '((eshell-connection-default-profile (eshell-path-env-list)) (tramp-connection-local-darwin-ps-profile (tramp-process-attributes-ps-args "-acxww" "-o" "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state=abcde" "-o" "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args") (tramp-process-attributes-ps-format (pid . number) (euid . number) (user . string) (egid . number) (comm . 52) (state . 5) (ppid . number) (pgrp . number) (sess . number) (ttname . string) (tpgid . number) (minflt . number) (majflt . number) (time . tramp-ps-time) (pri . number) (nice . number) (vsize . number) (rss . number) (etime . tramp-ps-time) (pcpu . number) (pmem . number) (args))) (tramp-connection-local-busybox-ps-profile (tramp-process-attributes-ps-args "-o" "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "stat=abcde" "-o" "ppid,pgid,tty,time,nice,etime,args") (tramp-process-attributes-ps-format (pid . number) (user . string) (group . string) (comm . 52) (state . 5) (ppid . number) (pgrp . number) (ttname . string) (time . tramp-ps-time) (nice . number) (etime . tramp-ps-time) (args))) (tramp-connection-local-bsd-ps-profile (tramp-process-attributes-ps-args "-acxww" "-o" "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args") (tramp-process-attributes-ps-format (pid . number) (euid . number) (user . string) (egid . number) (group . string) (comm . 52) (state . string) (ppid . number) (pgrp . number) (sess . number) (ttname . string) (tpgid . number) (minflt . number) (majflt . number) (time . tramp-ps-time) (pri . number) (nice . number) (vsize . number) (rss . number) (etime . number) (pcpu . number) (pmem . number) (args))) (tramp-connection-local-default-shell-profile (shell-file-name . "/bin/sh") (shell-command-switch . "-c")) (tramp-connection-local-default-system-profile (path-separator . ":") (null-device . "/dev/null"))))
 '(connection-local-criteria-alist '(((:application eshell) eshell-connection-default-profile) ((:application tramp :machine "localhost") tramp-connection-local-darwin-ps-profile) ((:application tramp :machine "Mac") tramp-connection-local-darwin-ps-profile) ((:application tramp) tramp-connection-local-default-system-profile tramp-connection-local-default-shell-profile)))
 '(custom-safe-themes '("98b4ef49c451350c28a8c20c35c4d2def5d0b8e5abbc962da498c423598a1cdd" default))
 '(package-selected-packages '(nord-theme gnu-elpa-keyring-update yaml-mode web-mode lsp-ui lsp-mode json-mode js2-mode rainbow-mode zop-to-char zenburn-theme which-key volatile-highlights vertico undo-tree super-save smartrep smartparens rainbow-delimiters projectile orderless operate-on-number nlinum move-text magit imenu-anywhere hl-todo git-timemachine git-modes gist flycheck expand-region exec-path-from-shell epl elisp-slime-nav editorconfig easy-kill discover-my-major diminish diff-hl crux consult company browse-kill-ring anzu ag ace-window))
 '(xterm-mouse-mode t))

(custom-theme-set-faces
 'nord-prlg
 '(default ((t (:inherit nil :extend nil :stipple nil :background "undefined" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default")))))

(provide-theme 'nord-prlg)
